# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfLife', '0004_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://s3.amazonaws.com/37assets/svn/765-default-avatar.png', max_length=1000),
        ),
    ]
