# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShelfLife', '0006_auto_20170806_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='F_items',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
